### ISSUE TITLE
multilayer vesicle doesn't define effective radius (Trac #843)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasmodels#139]
Documentation for multilayer vesicle says that it uses the outer shell radius as the effective radius when P(Q)*S(Q) is applied, but ER() is not defined, so no structure factor can be applied.

This feature was available in the !MultiShellModel in 3.1.2.

Note that the equation docs can be improved for this model.

Also, it should use n_shells rather than n_pairs since there is one fewer solvent layer than shell layer.

Migrated from http://trac.sasview.org/ticket/843
```json
{
    "status": "closed",
    "changetime": "2017-03-13T04:05:41",
    "_ts": "2017-03-13 04:05:41.916622+00:00",
    "description": "Documentation for multilayer vesicle says that it uses the outer shell radius as the effective radius when P(Q)*S(Q) is applied, but ER() is not defined, so no structure factor can be applied.\n\nThis feature was available in the !MultiShellModel in 3.1.2.\n\nNote that the equation docs can be improved for this model.\n\nAlso, it should use n_shells rather than n_pairs since there is one fewer solvent layer than shell layer.",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2017-02-01T23:51:58",
    "component": "sasmodels",
    "summary": "multilayer vesicle doesn't define effective radius",
    "priority": "major",
    "keywords": "",
    "milestone": "SasView 4.1.0",
    "owner": "pkienzle",
    "type": "defect"
}
```

**Comment by pkienzle** [comment]
Trac update at `2017/02/01 23:56:17`: **pkienzle** commented:

Sasview 3.1.2 supports polydispersity on thickness of shell and solvent interlayers plus core, but 4.0.1 does not.

**Comment by pkienzle** [comment]
Trac update at `2017/02/02 01:06:50`: **pkienzle** commented:

Pull request awaiting approval by someone who cares to check it.

The following shows that it is consistent with 4.0.1:

```text
python ../../sasmodels/sascomp multilayer_vesicle,multilayer_vesicle.py -random n_pairs="int(n_shells+0.5)" -pars
```

Run this from sasmodels-master/sasmodels/models, where sasmodels-master/ is a separate clone of the git repo for sasmodels, and sasmodels/ is on the ticket-853 branch.

If you are on a unix-like operating system, you can make a symlink to sascomp and save a few keystrokes:


```text
ln -s ~/src/sasmodels/sascomp ~/bin
sascomp multilayer_vesicle,multilayer_vesicle.py ...
```

**Comment by butlerpd** [comment]
Trac update at `2017/02/02 02:52:08`: 
* **butler** commented:

Actually, this is called a "vesicle" model. Thus "pairs" refers to the pairs of lipid monolayers required to make a single "bilayer" shell.  That said the model is valid for any solid shells (whether from a bilayer or something else) so shells works as a name as well.  Documentation will need to be very clear however about what is meant -- in particular since this will be used almost exclusively by membrane people it should be clear that one shell = 1 bilayer = 2 layers of lipids.


* **butler** changed description from:

> Documentation for multilayer vesicle says that it uses the outer shell radius as the effective radius when P(Q)*S(Q) is applied, but ER() is not defined, so no structure factor can be applied.
> 
> This feature was available in the MultiShellModel in 3.1.2.
> 
> Note that the equation docs can be improved for this model.
> 
> Also, it should use n_shells rather than n_pairs since there is one fewer solvent layer than shell layer.

to:

> Documentation for multilayer vesicle says that it uses the outer shell radius as the effective radius when P(Q)*S(Q) is applied, but ER() is not defined, so no structure factor can be applied.
> 
> This feature was available in the !MultiShellModel in 3.1.2.
> 
> Note that the equation docs can be improved for this model.
> 
> Also, it should use n_shells rather than n_pairs since there is one fewer solvent layer than shell layer.

**Comment by butlerpd** [comment]
Trac update at `2017/02/07 01:10:41`: 
* **butler** changed component from "SasView" to "sasmodels"
* **butler** changed owner from "" to "pkienzle"
* **butler** changed status from "new" to "assigned"

**Comment by butlerpd** [comment]
Trac update at `2017/03/05 23:38:13`: **butler** commented:

Actually I was wrong -- pairs does not refer to bilayers of a shell.  Actually it refers indeed to water+bilayer pairs.  However it considers the core water + bilayer to be the first pair while the second pair is the next water layer (now a shell itself) plus next bilayer etc.

Agree that shells is equivalent to pairs for purposes of calculations, but not sure it is less confusing. Indeed, this is a multilamellar vesicle model not a multi shell model.  There are other models that are multishell but they don't have "pairs" and instead are truly n_shells whereas we have 2*n_shells-1 shells. I think in fact pairs is better though perhaps n_layers or l_lamellae would be better?

Also worried about polydispersity.  This is a "highly non linear" model.  In particular we should not allow polydispersity on n since a) n can only take integer values and b) for n=1 tw must equal 0 so would need some logic in case the distribution in n includes 1 (very likely).  I would vote for NO polydispersity parameters on this model for now - or at best on R but that belongs to ticket SasView/sasview#873 and as Richard says would need to check carefully on how to do the vol normalization?

**Comment by RichardHeenan** [comment]
Trac update at `2017/03/06 17:37:50`: **richardh** commented:

Paul K asked -
(A) multilayer vesicle has volfraction parameter. How should this relate to the volfraction parameter in the hard sphere structure factor?

According to the docs, and the code, the model is normalised to Vt the "volume of the whole particle", so volfraction should be for the external particle, thus will be fine in S(Q) as is.

(B) The current code renames volfraction to volfraction_S for the structure factor volfraction in the combined model

Pass, the latest pull on my machine won't let me use an S(Q) with this model.
Richard

**Comment by pkienzle** [comment]
Trac update at `2017/03/09 23:48:55`: 
* **pkienzle** changed resolution from "" to "fixed"
* **pkienzle** changed status from "assigned" to "closed"

**Comment by butlerpd** [comment]
Trac update at `2017/03/13 04:05:41`: **butler** commented:

In changeset 5d23de23656b990e141f01721eb85cd0afaa4dc2:

```text
#!CommitTicketReference repository="sasmodels" revision="5d23de23656b990e141f01721eb85cd0afaa4dc2"
Fold caveats from original IGOR documentation back into sasmodels
version as requested on sasmodels pull request 27 addressing ticket 843.
Also reformated refs and authorship section as per ticket #106
```
