### ISSUE TITLE
use new orientation definition for asymmetric shapes (Trac #890)

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasmodels#147]
Migrated from http://trac.sasview.org/ticket/890
```json
{
    "status": "closed",
    "changetime": "2017-05-16T13:44:23",
    "_ts": "2017-05-16 13:44:23.646742+00:00",
    "description": "",
    "reporter": "pkienzle",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasModels Redesign",
    "time": "2017-03-21T13:38:48",
    "component": "sasmodels",
    "summary": "use new orientation definition for asymmetric shapes",
    "priority": "blocker",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "pkienzle",
    "type": "defect"
}
```

**Comment by pkienzle** [comment]
Trac update at `2017/03/21 13:45:45`: 
* **pkienzle** changed owner from "" to "pkienzle"
* **pkienzle** changed status from "new" to "assigned"

**Comment by pkienzle** [comment]
Trac update at `2017/03/21 15:12:47`: **pkienzle** changed milestone from "SasView 4.1.0" to "SasView 4.2.0"

**Comment by RichardHeenan** [comment]
Trac update at `2017/04/05 13:51:04`: **richardh** commented:

triaxial ellipsoid and the parrallelepiped models still need modifications to their effective radius calculation.

triaxial_ellipsoid no longer asks users to keep A<B<C, For ER() need sort so that a=<b=<c; then if b is closer to a than to c, then we are prolate, a,b are equatorial axes and c is polar; else for oblate, a is polar and b,c are equatorial. Note this then uses ER() for ellipsoid, which has different calcs for oblate & prolate.

The paralleliped ER() uses that for cylinder, which seems not to have different version for rod and disk. But likewise we could sort the axes for ER() which would possibly remove the a<b<c requirement on theses models, but this needs testing!

Summary of what Paul K has already done in this ticket, apart from sorting the 2d I(Q) calculation:

major refactoring of calc of I(Q) in - core_shell_bicelle, ellipsoid

redone equations in docu in - ellipsoid, triaxial_ellipsoid

**Comment by RichardHeenan** [comment]
Trac update at `2017/04/05 14:03:34`: **richardh** commented:

In changeset 4b0a294be46e951df4767202737d3e713c14ee28:

```text
#!CommitTicketReference repository="sasmodels" revision="4b0a294be46e951df4767202737d3e713c14ee28"
docu improvements re #147
```

**Comment by RichardHeenan** [comment]
Trac update at `2017/04/11 09:11:23`: **richardh** commented:

There are some notes in elliptical_cylinder about how many bins to use for orientational averages, these should be reviewed when we have he new integration scheme.

**Comment by pkienzle** [comment]
Trac update at `2017/05/16 13:44:23`: 
* **pkienzle** changed resolution from "" to "fixed"
* **pkienzle** changed status from "assigned" to "closed"
