### ISSUE TITLE
Erratic behaviour of Sum|Multi model in 4.1.2 (Trac #1099)

### ISSUE THREAD

**Issue by smk78** [SasView/sasmodels#174]
Affects 4.1.2.

This is a bit difficult to describe so bear with me:

One of my users wanted to fit the attached dataset to extract the peak position and width but in the presence of the power law regime at low-Q. Only later did they spot the broad_peak model, but this combines a power law and a Lorentzian. They wanted to  fit a Gaussian to the peak so used Sum|Multi to sum power_law and gaussian_peak (generating the attached broadgaussian plugin).

At some level this model can be used to generate a fit, but it is very 'clunky' and changes to the parameters do not always result in the model curve or !Chisq/Npts updating. We tried L-M and N-M optimisers.

Puzzled, I went off and tried the same thing in 3.1.2, summing powerlawabs and peakgauss (generating the attached broadgaussianold plugin). This works very nicely. It's crisp and responsive.

You need to try what I've just described to see what I mean.

As a workaround the user is installing 3.1.2. alongside 4.1.2.

Migrated from http://trac.sasview.org/ticket/1099
```json
{
    "status": "closed",
    "changetime": "2018-06-26T12:56:45",
    "_ts": "2018-06-26 12:56:45.597891+00:00",
    "description": "Affects 4.1.2.\n\nThis is a bit difficult to describe so bear with me:\n\nOne of my users wanted to fit the attached dataset to extract the peak position and width but in the presence of the power law regime at low-Q. Only later did they spot the broad_peak model, but this combines a power law and a Lorentzian. They wanted to  fit a Gaussian to the peak so used Sum|Multi to sum power_law and gaussian_peak (generating the attached broadgaussian plugin).\n\nAt some level this model can be used to generate a fit, but it is very 'clunky' and changes to the parameters do not always result in the model curve or !Chisq/Npts updating. We tried L-M and N-M optimisers.\n\nPuzzled, I went off and tried the same thing in 3.1.2, summing powerlawabs and peakgauss (generating the attached broadgaussianold plugin). This works very nicely. It's crisp and responsive.\n\nYou need to try what I've just described to see what I mean.\n\nAs a workaround the user is installing 3.1.2. alongside 4.1.2.",
    "reporter": "smk78",
    "cc": "",
    "resolution": "fixed",
    "workpackage": "SasView Bug Fixing",
    "time": "2018-04-25T10:56:14",
    "component": "sasmodels",
    "summary": "Erratic behaviour of Sum|Multi model in 4.1.2",
    "priority": "critical",
    "keywords": "",
    "milestone": "SasView 4.2.0",
    "owner": "",
    "type": "defect"
}
```

**Comment by smk78** [comment]
Trac update at `2018/04/25 10:57:29`: 
* **smk78** changed attachment from "" to "4801p0mm1D_rear.xml"
* **smk78** commented:

Example data file to fit

**Comment by smk78** [comment]
Trac update at `2018/04/25 10:58:20`: 
* **smk78** changed attachment from "" to "broadgaussian.py"
* **smk78** commented:

Sum|Multi model created in 4.1.2

**Comment by smk78** [comment]
Trac update at `2018/04/25 10:58:56`: 
* **smk78** changed attachment from "" to "broadgaussianold.py"
* **smk78** commented:

Sum|Multi model created in 3.1.2

**Comment by butlerpd** [comment]
Trac update at `2018/05/31 16:38:14`: **butler** commented:

follow up from meeting at IPRIME where I met Peter Schmidt from Lodge and Bates group who complained about a similar problem.  Suggested it looks like it was fitting only one of the two models in the combo.  Hitting fit gets a plot then hit compute with calculated parameters and the plots change.  He also says that going back to 4.0 works but after that the problem seems to have crept in.

**Comment by butlerpd** [comment]
Trac update at `2018/06/17 15:11:17`: **butler** commented:

After some "extensive" testing it appears that the specific problems are resolved already in 4.2.  Users should be asked to check to ensure we have not missed something. I used the release versions of 3.1.2 and 4.1.2 and the June 15 windows 64 build from Jenkins for the 4.2 tests.  I used the files attached here plus, for 4.2, I created a new sum/multiply model with the same two functions.  I will attach that to this ticket next. Some important notes:
1.  The sum/multiply model went through an intermediate stage in 4.1.2 so that the file created by 3.1.2 is different from that created by 4.1.2 is different from 4.2.  This last now only has ~6  lines, the first two being import statements, indicating the two models being combined and with what operator along with the name to give it and a description string.  The sasmodels infrastructure now takes care of everything else.
 a. !SasView 3.1.2 only recognizes the sum/multiply created by 3.1.2 and before
 b. !SasView 4.1.2 recognizes both the sum/multiply created by 3.1.2 and 4.1.2
 c. !SasView 4.2 recognizes all three (those created by 3.1.2, 4.1.2 and 4.2).  With 5.0 we maybe should stop supporting at least the old 3.1.2 sum/multiply models?  
2. !SasView 4.1.2 seems to have several issues - most of which seem to be resolved in 4.2.
 a. Fit runs the fit and returns values but does not update the plot until either Fit is run again or the Compute button is hit.
 b. From time to time it appears that hitting fitting does nothing and needs to be pressed a second time to launch.  This also seemed to happen in 4.2 but much less frequently?
 c. Very annoyingly, if the tab is started as a fit tab, the residual tab displays **TWO** ... different curves -- no idea what the second is actually plotting.  If instead the tab is started as a theory tab and then the data sent to the tab, the residual plot behaves correctly.
3. Note that a Guassian peak may not be the best way to model this broad shoulder in log space -- to capture that the width needs to be pretty large forcing the center of the Gaussian to be negative 0.05!! it can be fit reasonably by enforcing a q peak minimum of 0 but ...

**Comment by butlerpd** [comment]
Trac update at `2018/06/17 15:15:37`: 
* **butler** changed attachment from "" to "broadgaussian_SumMulti4p2.py"
* **butler** commented:

Sum|Multi model created in 4.2

**Comment by butlerpd** [comment]
Trac update at `2018/06/17 16:20:40`: **butler** commented:

I have pinged Peter Schmidt of UMN to verify that 4.2 has resolved the issues of this ticket.  We need to follow up with the user that first reported the issue as well.  Assuming they confirm we can resolve this ticket as fixed.

**Comment by smk78** [comment]
Trac update at `2018/06/26 09:52:31`: **smk78** commented:

Testing 4.2 Build 368 on W7 this issue now seems to be resolved, or at least greatly improved.

The L-M optimiser is perhaps not the best for this kind of model; N-M-S worked much better.

I have told the original user who reported the issue.

**Comment by smk78** [comment]
Trac update at `2018/06/26 12:56:25`: **smk78** commented:

After discussion with Paul I am closing this ticket. If the User reports adverse problems we will reopen.

**Comment by smk78** [comment]
Trac update at `2018/06/26 12:56:45`: 
* **smk78** changed resolution from "" to "fixed"
* **smk78** changed status from "new" to "closed"
