### ISSUE TITLE
Beta approximation for mixture models

### ISSUE THREAD

**Issue by pkienzle** [SasView/sasmodels#205]
Trac update at `2018/07/23 14:39:17`:

I'm hoping that mixture is something simple like beta = (<Fa> + <Fb>)²/(<Fa²> + <Fb²>) which gives:

                           I =  (<Fa²> + <Fb²>)⋅(1 + β(S - 1))                                       (1)

That would lets modify mixture model to return <F> as <Fa> + <Fb> and <F²> as <Fa²> + <Fb²>, and we would be able to use the result in product.  I don't know if that is a useful approximation though.

[I think it is OK, just have to accumulate <F> and <F²> as we go along. I rewrote equation (1) which was wrong in the email, Richard ]

_Originally posted by @RichardHeenan in https://github.com/SasView/sasmodels/issues/173#issuecomment-478234669_

**Comment by RichardHeenan** [comment]
I presume that mixture model is simply an extension of polydispersity in shape or size, so sum F1, and sum F2, assuming that the particles in the mixture all have the same S(Q).
Of course if different regions of a sample have differnt strucutres, then a simple sum of two I(Q0 would work.

**Comment by pkienzle** [comment]
... and R_eff and particle volume, with appropriate correction for hollow shapes and for relative scale.

Okay, it should be easy enough: set `have_Fq` on the mixture model if we are adding together components with `have_Fq` set, and define `MixureKernel.Fq` so that it calls Fq on the individual models.

**Comment by pkienzle** [comment]
Extending β approx. to multi-component mixtures such as (P1+P2+P3)@hardsphere should work as well:

    I_β = (∑I)(1 + β(S-1))

where I = φ <F²>/<V> is the usual scattering from an individual model P scaled by its volume fraction φ, and β = <F>²/<F²> is the combined β with F and F² averaged across all models weighted by φ.

This is just a simple extension from single shapes of different dimension to multiple shapes of different dimension, so it should work as well as you can expect from the β approx.

**Comment by yunliu01** [comment]
I assume that the calculation of F still have been divided by V_p due to the historical reason.
Here V_p is the volume of one individual object.
If this is still the case, the weighting average using phi would be the right one.

Note that phi is the probability function for each individual component based on the volume fraction.
It is not the real volume fraction of individual component in a solution.
The summation of all phi is one. (This is expected for a normalized probability function.)

With the framework of the beta approximation, this is right.

However, as the beta approximation itself is a first order approximation, it may quickly fail when things begin to deviate too much from one component spherical particle system with an isotropic interaction. It may be challenging to add constraints to the model itself.
However, I am wondering if it would be useful to add a few sentences to the help file to explain its limitation.

**Comment by pkienzle** [comment]
*F* contains contrast and volume, as it needs to for shapes with different SLD components, weighted by the polydispersity distribution *w*:
```
    F(r) = Δρ V(r) ⋅ 3 j1(q r)/(q r)
    F_avg = ∑ w(r) F(r) / ∑ w(r)
    F²_avg = ∑ w(r) F²(r) / ∑ w(r)
    V_avg = ∑ w(r) V(r) / ∑ w(r)
    R_avg = ∑ w(r) R(r) / ∑ w(r)
```
So the volume fraction *w(r)* associated with the individual *r* components of the polydispersity distribution are normalized to one, but the overall volume fraction φ for the spheres in solution in `P@S` is not, with `P = φ F²_avg  / V_avg`.

Similarly, when mixing cylinders and spheres, each model would need to indicate its own independent volume fraction in solution, so effectively the *w(r)* would normalize to φ for the spheres.

**Comment by yunliu01** [comment]
I do not know if my understanding of the code is correct.

Based on the information in the post, I would believe w(r) should be the number density ratio rather than volume fraction ratio. When the number ratio is multiplied by the particle volume, it becomes the volume fraction ratio.

**Comment by pkienzle** [comment]
Agreed, *w(r)* is the relative number of each particle, with scattering intensity for each *r* determined by contrast and particle volume *Δρ V(r)*.  

The scale factor *φ/<V(r)>* gives you the number density of scatters $n$ for the system, with

    I(q) = ∫ n(r) <FF*> dr = φ  ∫ w(r)<FF*> dr /  ∫ w(r)V(r) dr

This follows from *n(r) = w(r) N / V_t*, where *N* is the total number of particles, *V_t* is the total volume, and *φ = N <V(r)>/V_t* is the volume fraction of particles.

**Comment by yunliu01** [comment]
Sorry if I have too many naive questions about the code when I am trying to understand what is implemented for the polydispersity case. 

Based on "I(q) = ∫ n(r) <FF*> dr = φ  ∫ w(r)<FF*> dr /  ∫ w(r)V(r) dr", 
n(r) = w(r)*φ/∫ w(r)V(r)dr.

And n(r) is the number density distribution function.

If  φ=∫ w(r)V(r)dr, w(r) would be same as n(r) . 
Are both w(r) and n(r) the number density?
If w(r) is the volume fraction, n(r) and w(r) will be different.

If φ is not equal to∫ w(r)V(r)dr, n(r) is still similar to w(r) by one simple scaling parameter.
However, if w(r) is the volume fraction, due to r^3 dependence for the volume term, w(r) and n(r) would not differ only by one scaling constant.

I feel that I am puzzled. 
Well, this is not a surprise as I had been confused many times before.
It is quite possible that I misunderstood something here.

**Comment by pkienzle** [comment]
w(r) is the relative *number* of particles of size r, which scales with the number density n(r).  It is not the volume fraction of particles of size r.

Here is the derivation in gory detail. The books are no help because they skip over the trivial algebra, so I end up spending time re-deriving it every time I think about it.

φ is volume fraction, which is the integrated volume of all particles Vp divided by total volume Vt, 

    [1]  φ = Vp / Vt

In terms of particles, Vp is the number of particles N times the average particle volume <V(r)>, 

    [2]  Vp = N <V(r)>

The number density of particles, n, is the total number of particles divided by the total volume

    [3]  n = N / Vt

Since w(r) is a distribution on the number of particles that (ideally) sums to one, the number particles of particles of size r scales with w(r) as

    [4]  n(r) = w(r) / ∫w(r)dr  ⋅  N / Vt

Rewriting [1] as Vp =  φ Vt and substituting into [2] as φ Vt = N <V(r)>, we can solve for N/Vt as

    [5]  N/Vt = φ / <V(r)>

Putting this into [4], we get

    [6]  n(r) = w(r) / ∫w(r)dr  ⋅  φ / <V(r)>

Since w(r) is the relative number of particles of size r, the average volume is

    [7]  <V(r)> = ∫ w(r)V(r)dr / ∫ w(r)dr

which we can put into [6] to get the result

    [8]  n(r) = w(r) ⋅  φ / ∫ w(r)V(r)dr

The second half of this equation is independent of r and can slip out of the integral, so

    [9]  I(q) = ∫ n(r) <FF*> dr = φ  ∫ w(r)<FF*> dr /  ∫ w(r)V(r) dr

**Comment by yunliu01** [comment]
Thanks for explaining the details of the notation.

So w(r) is the normalized density distribution function, and n(r) is the absolute density function of different particles. Then everything makes sense. Thanks again for typing the details for this.

**Comment by smk78** [comment]
Is there still a reason for keeping this open?

**Comment by butlerpd** [comment]
Thanks @yunliu01. Indeed the things you mention would be a separate ticket and not with this is about. I will go ahead and close it then.
