### ISSUE TITLE
core_multi_shell model

### ISSUE THREAD

**Issue by Miradin** [SasView/sasmodels#369]
SasView version: 5.0
"core_multi_shell" model was working in 4.2.2 and is broken in 5.0.0 with more than 1 shell.

Proof:
* Use data fitting or simulation. 
* From category "Sphere" choose model "core_multi_shell".
* In parameters set 2 shells (n=2).
* Press 'Show Plot' button.
* Change parameters of second shell (SLD or thickness). Confirm.  Scattering curve change is expected, but no effect is observed.

With that SLD Profile is showing correctly.

With best regards,
Alex

**Comment by butlerpd** [comment]
Doing some testing I verified that this was not working as described in 5.0.0. However it seems to be working in 5.0.1 (and 5.0.4 just released).  I am going to move this to milestone sasmodels. 1.0.1 which was the version used in 5.0.1 though It is very possible that the issue was in how SasView GUI was handling the plotting.  Will then close this ticket
